language: python
jobs:
  include:
    - python: '3.7'
    - python: '2.7'
    - name: 'Python: 2.3'
      # python 2.3 not available in travis
      install:
        - cd ..
        - curl -O https://www.python.org/ftp/python/2.3.7/Python-2.3.7.tgz
        - tar xzf Python-2.3.7.tgz
        - cd Python-2.3.7
        # We need to disable FORTIFY_SOURCE to compile python 2.3
        # cf. https://bugs.launchpad.net/ubuntu/+source/gcc-defaults/+bug/286334
        - ./configure BASECFLAGS=-U_FORTIFY_SOURCE
        - make
        - export PATH=$(pwd):$PATH
        - cd ../elfesteem
        - python -c 'import sys;print(sys.version)'
      script:
        - python ./tests/test_all.py
      after_success:
        - true # coverage needs python >= 2.6
    - python: 'pypy3'
    - python: 'pypy'
    - python: '3.8'
    - python: '3.4'
install:
  - pip install coverage codecov
before_script:
  export PYTHONPATH=$PYTHONPATH:$(pwd)
script:
  - coverage run ./tests/test_all.py
  # We don't use e.g. tox for non-regression tests, because we want to have
  # a script that works with old python too, and tox needs python2.5
  # python2.4 ./tests/test_all.py will work fine :-)
  # Note that coverage is incompatible with python 3.2, cf.
  # https://github.com/menegazzo/travispy/issues/20
after_success:
  - codecov
