# This workflow compares the outputs of elfesteem with native tools on the OS

name: Native tools

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  examples:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-12", "macos-13"]
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Comparison with otool
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        zsh ./tests/examples_macos.sh
